#define yy_create_buffer estimo_create_buffer
#define yy_delete_buffer estimo_delete_buffer
#define yy_scan_buffer estimo_scan_buffer
#define yy_scan_string estimo_scan_string
#define yy_scan_bytes estimo_scan_bytes
#define yy_flex_debug estimo_flex_debug
#define yy_init_buffer estimo_init_buffer
#define yy_flush_buffer estimo_flush_buffer
#define yy_load_buffer_state estimo_load_buffer_state
#define yy_switch_to_buffer estimo_switch_to_buffer
#define yyin estimoin
#define yyleng estimoleng
#define yylex estimolex
#define yyout estimoout
#define yyrestart estimorestart
#define yytext estimotext
#define yywrap estimowrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
static yyconst short int yy_accept[244] =
    {   0,
        0,    0,    0,    0,    0,    0,   85,   83,   80,   81,
       16,   83,   83,   82,   83,   82,   82,   82,   72,   72,
       72,   33,   10,   17,    9,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   83,   78,   76,   75,   78,   70,
       65,   68,   69,   69,   69,   67,   70,   66,   66,   52,
       66,   66,   66,   66,   80,   15,    0,   73,    0,    0,
        0,    0,    0,   11,   18,    0,   74,    0,   72,   72,
       72,    0,   13,    8,   14,   71,   71,   71,   71,   71,
       71,   71,   71,   71,    4,   71,   71,   71,    1,   35,

       71,   71,   71,   71,   71,   71,    6,   71,   71,   12,
       77,   65,   68,   67,    0,    0,    0,    0,    0,   67,
       67,    0,   64,   66,   62,   63,   66,   66,   66,   66,
       66,    0,   28,    0,   26,    0,    0,    0,   79,   72,
        0,    0,   45,   71,   71,   71,   22,   71,   71,   71,
       71,   71,   71,    5,   71,   71,   37,   71,   71,   71,
       71,   71,    0,    0,    0,    0,    0,   67,   55,   66,
       66,   53,   61,    0,    0,    0,    0,    0,   44,   43,
       23,   71,   71,   71,   71,   32,   71,    2,   39,   71,
       34,   41,   71,   38,    7,   71,   71,    0,    0,   48,

       51,    0,   66,   58,   57,   56,   66,   54,    0,   27,
        0,    0,   42,   71,   71,   25,   31,   20,   36,   40,
       71,    3,    0,    0,    0,   66,   59,   30,   29,    0,
       24,   71,   19,   50,   49,    0,   60,    0,   21,   47,
        0,   46,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    1,   11,
       11,   12,   13,   11,   14,   15,   16,   17,   18,   19,
       20,   20,   20,   21,   20,   22,   20,   23,   24,   25,
       26,   27,    1,    8,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   33,   33,   37,   38,   39,   40,   41,
       33,   33,   42,   43,   33,   33,   44,   33,   45,   33,
        1,    8,    1,    8,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   33,   68,   69,
       70,   33,   71,   72,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[73] =
    {   0,
        1,    2,    1,    2,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    3,    3,    3,
        3,    3,    2,    2,    2,    2,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1
    } ;

static yyconst short int yy_base[250] =
    {   0,
        0,    0,   71,   73,   85,    0,  430,  431,   75,  431,
      403,  422,  110,  431,  417,  399,  397,   66,  149,  162,
      170,  431,  398,  397,  396,    0,  381,  388,  372,  390,
      381,  352,  139,  354,  356,  112,  361,   20,  351,  111,
      131,  350,  348,  355,  336,  431,  431,  431,  391,  431,
      172,  403,  431,  181,  156,  193,  402,    0,   93,    0,
      162,  357,  344,  355,  215,  431,  395,  431,  336,  338,
      340,  345,  342,  431,  431,  353,  431,  391,  205,  213,
      223,  228,  431,  431,  431,    0,  351,  353,  325,  359,
      350,  337,  322,  335,    0,  320,  336,  319,    0,    0,

      329,  331,  312,  324,  314,  326,    0,  326,  320,  431,
      431,  245,  371,  236,  322,  318,  320,  310,  308,  242,
      250,  365,  431,    0,    0,    0,  310,  304,  307,  302,
      313,  311,  431,  296,  431,  305,  317,  355,  431,  256,
      230,  336,  431,  313,  321,  288,    0,  317,  305,  300,
      301,  298,  283,    0,  177,  296,    0,  286,  279,  282,
      296,  284,  288,  289,  287,  288,  282,  262,  280,  235,
      269,    0,    0,  287,  282,  274,  299,  309,  431,  431,
        0,  286,  277,  296,  269,    0,  268,    0,    0,  307,
        0,    0,  257,    0,    0,  256,  270,  265,  270,  431,

      431,  258,  258,    0,    0,    0,  265,    0,  258,  431,
      263,  275,  431,  259,  227,    0,    0,    0,    0,    0,
      239,    0,  229,  230,  219,  204,    0,  431,  431,  208,
        0,  176,    0,  431,  431,  164,    0,  183,    0,  431,
      164,  431,  431,  295,  298,  300,  304,   81,  308
    } ;

static yyconst short int yy_def[250] =
    {   0,
      243,    1,  244,  244,  243,    5,  243,  243,  243,  243,
      243,  245,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  247,  248,  248,  248,
      248,  248,  248,  248,  243,  243,  245,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  249,  243,  243,
      243,  243,  243,  243,  243,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  247,  243,  248,  248,  248,  248,  248,  248,  248,
      248,  243,  243,  243,  243,  243,  243,  249,  243,  243,
      243,  243,  243,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  243,  243,  243,  243,  243,  243,  248,  248,
      248,  248,  248,  243,  243,  243,  243,  243,  243,  243,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  243,  243,  243,

      243,  243,  248,  248,  248,  248,  248,  248,  243,  243,
      243,  243,  243,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  243,  243,  243,  248,  248,  243,  243,  243,
      246,  246,  246,  243,  243,  243,  248,  243,  246,  243,
      243,  243,    0,  243,  243,  243,  243,  243,  243
    } ;

static yyconst short int yy_nxt[504] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,    8,   14,   15,
       14,   14,   14,   16,   17,   18,   19,   20,   19,   19,
       19,   21,   22,   14,   23,   24,   25,   26,   26,   27,
       26,   26,   26,   26,   26,   26,   28,   26,   26,   26,
       29,   30,   26,   31,   26,    8,   26,   32,   33,   34,
       35,   36,   26,   26,   37,   26,   26,   38,   39,   26,
       26,   40,   26,   26,   41,   42,   43,   44,   26,   26,
       14,   45,   47,   48,   47,   48,   65,   77,   65,  100,
      101,   78,   49,  124,   49,   50,   51,   52,   51,   50,
       50,   50,   50,   50,   50,   53,   53,   54,   54,   55,

       53,   56,   56,   56,   56,   56,   56,   53,   57,   50,
       50,   50,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   59,   58,   58,   58,   58,   58,   58,   58,
       50,   58,   60,   61,   58,   58,   58,   58,   62,   58,
       63,   58,   58,   58,   58,   58,   58,   58,   58,   64,
       58,   58,   58,   58,   58,   53,   50,   69,   97,   70,
       71,  125,  126,   79,   72,   80,   80,   80,   80,   80,
       80,  103,   98,  112,  104,  112,   79,   73,   80,   80,
       80,   80,   81,   80,   79,   93,   80,   80,   80,   80,
       80,   80,   94,  105,  190,  191,  106,  114,  114,  114,

      114,  114,  114,  115,  116,  117,  118,  120,  242,  121,
      121,  121,  121,  121,  121,  127,   65,  119,   65,  241,
      128,  140,  140,  140,  140,  140,  140,   79,  240,   80,
       80,   80,   80,   80,   80,  239,  238,   79,   82,   80,
       80,   80,   80,   80,   80,  142,  112,  178,  112,  143,
      120,  179,  121,  121,  121,  121,  121,  121,  168,  168,
      168,  168,  168,  168,  120,  237,  121,  121,  121,  121,
      121,  121,  140,  140,  140,  140,  140,  140,  168,  168,
      168,  168,  168,  168,  236,  204,  235,  205,  234,  233,
      232,  141,  206,  231,  207,   46,   46,   46,   46,   67,

       67,   67,   86,   86,  122,  122,  122,  122,  138,  138,
      138,  138,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  139,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  123,  167,  166,
      165,  164,  163,  113,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  139,  137,  136,  135,  134,  133,  132,

       68,  131,  130,  129,  123,  113,  111,  110,  109,  108,
      107,  102,   99,   96,   95,   92,   91,   90,   89,   88,
       87,   85,   84,   83,   76,   75,   74,   68,   66,  243,
        7,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243
    } ;

static yyconst short int yy_chk[504] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    9,   18,    9,   38,
       38,   18,    3,  248,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,   13,   36,   13,
       13,   59,   59,   19,   13,   19,   19,   19,   19,   19,
       19,   40,   36,   51,   40,   51,   20,   13,   20,   20,
       20,   20,   20,   20,   21,   33,   21,   21,   21,   21,
       21,   21,   33,   41,  155,  155,   41,   54,   54,   54,

       54,   54,   54,   55,   55,   55,   55,   56,  241,   56,
       56,   56,   56,   56,   56,   61,   65,   55,   65,  238,
       61,   79,   79,   79,   79,   79,   79,   80,  236,   80,
       80,   80,   80,   80,   80,  232,  230,   81,   21,   81,
       81,   81,   81,   81,   81,   82,  112,  141,  112,   82,
      114,  141,  114,  114,  114,  114,  114,  114,  120,  120,
      120,  120,  120,  120,  121,  226,  121,  121,  121,  121,
      121,  121,  140,  140,  140,  140,  140,  140,  168,  168,
      168,  168,  168,  168,  225,  170,  224,  170,  223,  221,
      215,   81,  170,  214,  170,  244,  244,  244,  244,  245,

      245,  245,  246,  246,  247,  247,  247,  247,  249,  249,
      249,  249,  212,  211,  209,  207,  203,  202,  199,  198,
      197,  196,  193,  190,  187,  185,  184,  183,  182,  178,
      177,  176,  175,  174,  171,  169,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  156,  153,  152,  151,
      150,  149,  148,  146,  145,  144,  142,  138,  137,  136,
      134,  132,  131,  130,  129,  128,  127,  122,  119,  118,
      117,  116,  115,  113,  109,  108,  106,  105,  104,  103,
      102,  101,   98,   97,   96,   94,   93,   92,   91,   90,
       89,   88,   87,   78,   76,   73,   72,   71,   70,   69,

       67,   64,   63,   62,   57,   52,   49,   45,   44,   43,
       42,   39,   37,   35,   34,   32,   31,   30,   29,   28,
       27,   25,   24,   23,   17,   16,   15,   12,   11,    7,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "estimo.l"
#define INITIAL 0
#line 2 "estimo.l"
/*
   Estimo Lexical Analyzer
   SharpEye Studio Project
   Copyright (C) George Vafiadis
   email: vafiadis@ieee.org
   web: http://sharpeye.borelspace.com
   Under GPL v2 License.
*/

#pragma warning(disable : 4996)

#include <cstdio>
#include <math.h>
#include <vector>
#include <string.h>

class Entity;

#include "estimo_yacc.h"

extern int isatty(int)
{return 0;}

extern YYSTYPE estimolval;
int lines = 0;

#define COMMENT 1

#define ASM 2

#line 607 "lex.estimo.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 32 "estimo.l"

#line 760 "lex.estimo.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 244 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 431 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "estimo.l"
{return T_IF;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "estimo.l"
{return T_ELSE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "estimo.l"
{return T_WHILE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "estimo.l"
{return T_DO;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "estimo.l"
{return T_FOR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "estimo.l"
{return T_FORTO;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "estimo.l"
{return T_FORSTEP;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "estimo.l"
{return T_EQ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "estimo.l"
{return T_GT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "estimo.l"
{return T_LT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "estimo.l"
{return T_AND;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "estimo.l"
{return T_OR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "estimo.l"
{return T_LE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "estimo.l"
{return T_GE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "estimo.l"
{return T_NE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "estimo.l"
{return T_NOT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "estimo.l"
{return T_SET;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "estimo.l"
{return T_ARROW;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "estimo.l"
{return T_UPDATE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "estimo.l"
{return T_CHECK;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "estimo.l"
{return T_PATTERN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 "estimo.l"
{return T_SAD;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 "estimo.l"
{return T_COST;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 "estimo.l"
{return T_LENGTH;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 "estimo.l"
{return T_WINID;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "estimo.l"
{return T_IFS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "estimo.l"
{return T_ELSES;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "estimo.l"
{return T_DOS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "estimo.l"
{return T_WHILES;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "estimo.l"
{return T_BREAK_SHARP;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "estimo.l"
{return T_BREAK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "estimo.l"
{return T_CASE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 65 "estimo.l"
{return T_SEMICOL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "estimo.l"
{return T_FUN_LOG2;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "estimo.l"
{return T_FUN_LN;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "estimo.l"
{return T_FUN_LOG10; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "estimo.l"
{return T_FUN_POW;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "estimo.l"
{return T_FUN_SQRT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "estimo.l"
{return T_FUN_FABS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "estimo.l"
{return T_FUN_PRINT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "estimo.l"
{return T_MVC_MODE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "estimo.l"
{return T_MODE_16x16;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "estimo.l"
{return T_MODE_8x16;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "estimo.l"
{return T_MODE_16x8;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "estimo.l"
{return T_MODE_8x8;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "estimo.l"
{BEGIN ASM;return T_ASSEMBLY;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "estimo.l"
{return T_POINTS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "estimo.l"
{return T_DEF;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "estimo.l"
{return T_CHK;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "estimo.l"
{return T_BEGIN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "estimo.l"
{BEGIN 0; return T_END;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "estimo.l"
{return T_BRUNCH;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "estimo.l"
{return T_JMP;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "estimo.l"
{return T_HALT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "estimo.l"
{return T_CHK;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "estimo.l"
{return T_LT; /* compare R < Num */}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "estimo.l"
{return T_GT; /* compare R > Num */}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "estimo.l"
{return T_EQ; /* compare R == Num */}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "estimo.l"
{return T_NE; /* compare R != Num */}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "estimo.l"
{return T_CHKJMP;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "estimo.l"
{return T_SAD;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "estimo.l"
{return T_MX;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "estimo.l"
{return T_MY;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "estimo.l"
{++lines;return T_ENDL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "estimo.l"
{}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "estimo.l"
{strncpy(estimolval.str, yytext, 79); return T_ID;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "estimo.l"
{estimolval.n = (float)atof(yytext); return T_NUM;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 101 "estimo.l"
{lines += strlen(yytext); return T_ENDL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "estimo.l"
{return yytext[0];}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 103 "estimo.l"
{}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "estimo.l"
{ strncpy(estimolval.str, yytext, 79); return T_ID;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "estimo.l"
{estimolval.n = (float)atof(yytext); return T_NUM;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 109 "estimo.l"
{strcpy(estimolval.str, yytext); return T_STRING;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 111 "estimo.l"
{BEGIN COMMENT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 "estimo.l"
{ ++lines; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 "estimo.l"
{}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 114 "estimo.l"
{ BEGIN 0; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "estimo.l"
{}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 117 "estimo.l"
{++lines;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 119 "estimo.l"
{}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 120 "estimo.l"
{++lines;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "estimo.l"
{return yytext[0];}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 122 "estimo.l"
{}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "estimo.l"
ECHO;
	YY_BREAK
#line 1263 "lex.estimo.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(ASM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 244 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 244 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 243);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 123 "estimo.l"


/// When the input exhausted (end of file)
int yywrap()
{
 return 1;
}

