prefix=/usr/local
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
ARCH=X86
SYS=CYGWIN
CC=gcc
CFLAGS=-O4 -ffast-math  -Wall -I. -mno-cygwin -DHAVE_MMX -DHAVE_SSE3 -DARCH_X86 -DSYS_CYGWIN -s -fomit-frame-pointer
ALTIVECFLAGS=
LDFLAGS= -mno-cygwin -lvfw32 -s
AS=nasm
ASFLAGS=-O2 -f win32 -DPREFIX -DHAVE_SSE3
GTK=no
EXE=.exe
VIS=no
HAVE_GETOPT_LONG=1
DEVNULL=NUL
ECHON=echo -n
CONFIGURE_ARGS=
